services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
        - VITE_REACT_APP_API_URL=http://localhost:5000
      # - VITE_REACT_APP_API_URL=http://backend:5000
    networks:
      - app-network
    depends_on:
      - backend

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge